baseURL = "https://barryyan.github.io"
languageCode = "en-us"
title = "Barry's Blog"
theme = "dream"

enableRobotsTXT = true

hasCJKLanguage = true

# disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # background = "black"
  # backgroundImage = ""
  linkColor = "seagreen"

  author = "Barry"
  description = "Barry's Blog"
  avatar = ""
  motto = "What kind of person you are depends on the decisions you make."
  
  email = "barry.yanshg@gmail.com"
  github = "barryyan"
  # linkedin = ""
  # codepen = ""

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true