baseURL = "https://barryyan.github.io"
languageCode = "en-US"
defaultContentLanguage = "zh"
title = "天心阁"
theme = "dream"

enableRobotsTXT = true

hasCJKLanguage = true

# disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # background = "black"
  backgroundImage = "/me/bg.jpeg"
  linkColor = "deepskyblue"

  author = "苏夏天心"
  description = "天地人心"
  avatar = "/me/avatar.jpg"
  motto = "你是什么样的人, 取决于你所做的决定!"

  rss = true
  
  email = "barry.yanshg@gmail.com"
  github = "barryyan"
  # enable github issue comments
  repository = "BarryYan/barryyan.github.io"
  
  # linkedin = ""
  # codepen = ""

  # showSummaryCoverInPost = true

  siteStartYear = 2019

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "lightskyblue"
  darkNav = true
  dark404Button = true
