baseURL = "https://barryyan.github.io"
languageCode = "en-US"
defaultContentLanguage = "zh"
title = "天心阁"
theme = "dream"

enableRobotsTXT = true

hasCJKLanguage = true

# disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # background = "black"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "天心"
  description = "天地人心"
  avatar = "/me/avatar.jpg"
  motto = "你是什么样的人, 取决于你所做的决定!"
  
  email = "barry.yanshg@gmail.com"
  github = "barryyan"
  # linkedin = ""
  # codepen = ""

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true